[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 可选：如果你有环境变量
# [context.production.environment]
#   REACT_APP_FIREBASE_API_KEY = "your_firebase_api_key"
#   REACT_APP_FIREBASE_AUTH_DOMAIN = "your_project.firebaseapp.com"
#   REACT_APP_FIREBASE_PROJECT_ID = "your_project_id"
#   REACT_APP_FIREBASE_STORAGE_BUCKET = "your_project.appspot.com"
#   REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "your_sender_id"
#   REACT_APP_FIREBASE_APP_ID = "your_app_id"
